### ISSUE TITLE
Unable to build on Arch with gcc 15.1.1 - src/cg_isel.cpp:1784:45: error: narrowing conversion of ‘-3’ from ‘int’ to ‘unsigned char’ [-Wtemplate-body]

### ISSUE THREAD

**Issue by gazsp** [pubby/nesfab#38]
```
~/Documents/Development/opensource/nesfab #v1.6 !4
> make

CXX obj/cg_isel.o
g++ -std=c++20 -pthread -Wall -Wextra -Wno-unused-parameter -Wno-unknown-warning-option -Wno-narrowing -Wno-missing-field-initializers -Wno-missing-braces -Wno-unused-command-line-argument -fmax-errors=3 -ftemplate-depth=100 -pipe -Isrc -DVERSION=\""1.6"\" -DGIT_COMMIT=\""tags/v1.6-dirty"\" -mpopcnt -msse4 -mcx16 -mmovbe -O0 -g -c -o obj/cg_isel.o src/cg_isel.cpp
src/cg_isel.cpp: In function ‘void isel::eq_store(ssa_ht)’:
src/cg_isel.cpp:1784:45: error: narrowing conversion of ‘-3’ from ‘int’ to ‘unsigned char’ [-Wtemplate-body]
 1784 |             eq_branch<O::restrict_to<~REGF_X>, fail, success>(h);
      |                                             ^
src/cg_isel.cpp:1786:45: error: narrowing conversion of ‘-3’ from ‘int’ to ‘unsigned char’ [-Wtemplate-body]
 1786 |             eq_branch<O::restrict_to<~REGF_X>, success, fail>(h);
      |                                             ^
src/cg_isel.cpp: In function ‘void isel::lt_store(ssa_ht)’:
src/cg_isel.cpp:2241:41: error: narrowing conversion of ‘-3’ from ‘int’ to ‘unsigned char’ [-Wtemplate-body]
 2241 |         lt_branch<O::restrict_to<~REGF_X>, fail, success, LTE>(h);
      |                                         ^
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-unused-command-line-argument’ may have been intended to silence earlier diagnostics
cc1plus: note: unrecognized command-line option ‘-Wno-unknown-warning-option’ may have been intended to silence earlier diagnostics
make: *** [Makefile:210: obj/cg_isel.o] Error 1
```

```
~/Documents/Development/opensource/nesfab #v1.6 !4                                                                                                                                        
> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=ada,c,c++,d,fortran,go,lto,m2,objc,obj-c++,rust,cobol --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://gitlab.archlinux.org/archlinux/packaging/packages/gcc/-/issues --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 15.1.1 20250425 (GCC) 
```

**Comment by pubby** [comment]
This should be fixed by the 1.7 release.

**Comment by claui** [comment]
@pubby Any news on this?

**Comment by pubby** [comment]
@claui Are you still having the issue in 1.8?

**Comment by claui** [comment]
> Are you still having the issue in 1.8?

Just noticed that the error was on my end, I forgot to unset `CXX` (to make it point at `/usr/bin/c++` again)!

The issue can be closed now.
